import React from 'react';
import './DesignPrivacy.css';

const DesignPrivacy = () => {
    return (
        <div className="privacy-policy">
            <h1>DesignHype - Privacy Policy</h1>
            <p>Effective date: May 20, 2024</p>

            <p>
                <b>Introduction</b>
                <br />

                Welcome to <b>DesignHype</b>.
                <br />

                DesignHype (“us”, “we”, or “our”) operates at (https://www.designhype.xyz/) (hereinafter referred to as “<b>Service</b>”).
                <br />
                Our Privacy Policy governs your visit to (https://www.designhype.xyz/) and explains how we collect, safeguard, and disclose information that results from your use of our Service.
                <br />
                We use your data to provide and improve Service. By using the Service, you agree to the collection and use of information per this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
                <br />
                Our Terms and Conditions (“<b>Terms</b>”) govern all use of our Service and together with the Privacy Policy constitute your agreement with us (“<b>Agreement</b>”).
                <br />
                <p>
                    <h3>1. Definitions</h3>

                    <b>SERVICE</b> means the [https://www.designhype.xyz](https://www.designhype.xyz/) website operated by DesignHype
                    <br />
                    <b>PERSONAL DATA</b> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
                    <br />
                    <b>USAGE DATA</b> is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                    <br />
                    <b>COOKIES</b> are small files stored on your device (computer or mobile device).
                    <br />
                    <b>DATA CONTROLLER</b> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and how any personal data are, or are to be, processed. For this Privacy Policy, we are a Data Controller of your data.
                    <br />
                    <b>DATA PROCESSORS (OR SERVICE PROVIDERS)</b> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers to process your data more effectively.
                    <br />
                    <b>DATA SUBJECT</b> is any living individual who is the subject of Personal Data.
                    <br />
                    <b>THE USER</b> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
                    <br />
                </p>
                <p>
                    <b>2. Information Collection and Use</b>
                    <br />
                    We collect several different types of information for various purposes to provide and improve our Service to you.
                    <br />
                    3. <b>Types of Data Collected</b>
                    <br />
                    <b>Personal Data</b>
                    <br />
                    While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“<b>Personal Data</b>”). Personally identifiable information may include, but is not limited to:
                    <br />
                    1. Email address
                    <br />
                    2. Cookies and Usage Data
                    <br />
                    We may use your Data to contact you with newsletters, marketing or promotional materials, and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.
                    <br />
                    <b>Usage Data</b>
                    <br />
                    We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device (“<b>Usage Data</b>”).
                    <br />
                    This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                    <br />
                    When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device's unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
                    <br />

                    <h3> Tracking Cookies Data </h3>

                    We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
                    <br />
                    Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags, and scripts to collect and track information and to improve and analyze our Service.
                    <br />
                    You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
                    <br />
                    Examples of Cookies we use:
                    <br />
                    3. <b>Session Cookies:</b> We use Session Cookies to operate our Service.
                    <br />
                    4. <b>Preference Cookies:</b> We use Preference Cookies to remember your preferences and various settings.
                    <br />
                    5. <b>Security Cookies:</b> We use Security Cookies for security purposes.
                    <br />
                    6. <b>Advertising Cookies:</b> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.
                    <br />
                </p>
                <p>
                    4. <b>Use of Data</b>
                    <br />
                    DesignHype uses the collected data for various purposes:
                    <br />
                    1. to provide and maintain our Service;
                    <br />
                    2. to notify you about changes to our Service;
                    <br />
                    3. to allow you to participate in interactive features of our Service when you choose to do so;
                    <br />
                    4. to provide customer support;
                    <br />
                    5. to gather analysis or valuable information so that we can improve our Service;
                    <br />
                    6. to monitor the usage of our Service;
                    <br />
                    7. to detect, prevent, and address technical issues;
                    <br />
                    8. to fulfill any other purpose for which you provide it;
                    <br />
                    9. to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;
                    <br />
                    10. to provide you with notices about your account and/or subscription, including expiration and renewal notices, email instructions, etc.;
                    <br />
                    11. to provide you with news, special offers, and general information about other goods, services, and events that we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;
                    <br />
                    12. in any other way we may describe when you provide the information;
                    <br />
                    13. for any other purpose with your consent.
                    <br />
                    14. <b>Retention of Data</b>
                    <br />
                    We will retain your Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                    <br />
                    We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.
                    <br />
                    1. <b>Transfer of Data</b>
                    <br />
                    Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
                    <br />
                    If you are located outside the United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to the United States and process it there.
                    <br />
                    Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
                    <br />
                    DesignHype will take all the steps reasonably necessary to ensure that your data is treated securely and by this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
                    <br />
                    2. <b>Disclosure of Data</b>
                    <br />
                    We may disclose personal information that we collect, or you provide:
                    <br />
                    1. <h3>Disclosure for Law Enforcement</h3>

                    Under certain circumstances, we may be required to disclose your Data if required to do so by law or in response to valid requests by public authorities.

                    2. <h3>Business Transaction</h3>

                    If we or our subsidiaries are involved in a merger, acquisition, or asset sale, your Data may be transferred.
                    <br />
                    3. <b>Other cases. We may disclose your information also:</b>
                    <br />
                    1. to our subsidiaries and affiliates;
                    <br />
                    2. to contractors, service providers, and other third parties we use to support our business;
                    <br />
                    3. to fulfill the purpose for which you provide it;
                    <br />
                    4. for the purpose of including your company’s logo on our website;
                    <br />
                    5. for any other purpose disclosed by us when you provide the information;
                    <br />
                    6. with your consent in any other cases;

                    <br />
                    <h3> 3. Security of Data</h3>

                    The security of your data is important to us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.

                    <br />
                    <h3> 4. Your Data Protection Rights Under the General Data Protection Regulation (GDPR) </h3>

                    If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR. – See more at [GDPR](https://eur-lex.europa.eu/eli/reg/2016/679/oj).
                    <br />
                    We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
                    <br />
                    If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at [mahalabizz@gmail.com](mailto:mahalabizz@gmail.com).
                    <br />
                    In certain circumstances, you have the following data protection rights:
                    <br />
                    1. The right to access, update or delete the information we have on you.
                    <br />
                    2. The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.
                    <br />
                    3. The right to object. You have the right to object to our processing of your Personal Data.
                    <br />
                    4. The right of restriction. You have the right to request that we restrict the processing of your personal information.
                    <br />
                    5. The right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable, and commonly used format.
                    <br />
                    6. The right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information.
                    <br />
                    Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not be able to provide Service without some necessary data.
                    <br />
                    You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).

                    <br />
                    <h3> 5. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)</h3>

                    CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law’s reach stretches well beyond California to require a person or company in the United States (and conceivably the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy. – See more at: [CalOPPA](https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/).
                    <br />
                    According to CalOPPA, we agree to the following:
                    <br />
                    1. Users can visit our site anonymously.
                    <br />
                    2. Our Privacy Policy link includes the word “Privacy”, and can easily be found on the page specified above on the home page of our website.
                    <br />
                    3. Users will be notified of any privacy policy changes on our Privacy Policy Page.
                    <br />
                    4. Users are able to change their personal information by emailing us at [mahalabizz@gmail.com](mailto:mahalabizz@gmail.com).
                    <br />
                    <b>Our Policy on “Do Not Track” Signals:</b>
                    <br />
                    We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.
                    <br />
                    You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.

                    <br />
                    <h3> 6. Your Data Protection Rights under the California Consumer Privacy Act (CCPA)</h3>

                    If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data, and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:
                    <br />
                    <b>What personal information do we have about you?</b> If you make this request, we will return to you:
                    <br />
                    1. The categories of personal information we have collected about you.
                    <br />
                    2. The categories of sources from which we collect your personal information.
                    <br />
                    3. The business or commercial purpose for collecting or selling your personal information.
                    <br />
                    4. The categories of third parties with whom we share personal information.
                    <br />
                    5. The specific pieces of personal information we have collected about you.
                    <br />
                    6. A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.
                    <br />
                    7. A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.
                    <br />
                    Please note, that you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.
                    <br />
                    
                    2. <b>To delete your personal information</b>. If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.
                    <br />
                    3. <b>To stop selling your personal information</b>. We don't sell or rent your personal information to any third parties for any purpose. You are the only owner of your Personal Data and can request disclosure or deletion at any time.
                    <br />
                    Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services that require the usage of your personal information to function. But in no circumstances, we will discriminate against you for exercising your rights.
                    <br />
                    To exercise your California data protection rights described above, please send your request(s) by one of the following means:
                    <br />
                    By email: mahalabizz@gmail.com
                    <br />

                    Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To find out more, visit the official California Legislative Information website. The CCPA took effect on 01/01/2020.

                    <br />
                    <h3> 7. Service Providers</h3>

                    We may employ third-party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services, or assist us in analyzing how our Service is used.
                    <br />
                    These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.

                    <br />
                    <h3> 8. Analytics</h3>

                    We may use third-party Service Providers to monitor and analyze the use of our Service.
                    <br />
                    <b>Google Analytics</b>
                    <br />
                    Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.
                    <br />
                    For more information on the privacy practices of Google, please visit the [Google Privacy Terms](https://policies.google.com/privacy?hl=en) web page.
                    <br />
                    We also encourage you to review Google's policy for safeguarding your data: [Google Analytics Data Safeguarding](https://support.google.com/analytics/answer/6004245).
                    <br />

                    <h3> 9. Behavioral Remarketing</h3>

                    DesignHype uses remarketing services to advertise on third-party websites to you after you visit our Service. We and our third-party vendors use cookies to inform, optimize, and serve ads based on your past visits to our Service.
                    <br />
                    <b>Google Ads (AdWords)</b>
                    <br />
                    Google Ads (AdWords) remarketing service is provided by Google Inc. You can opt out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the [Google Ads Settings](http://www.google.com/settings/ads) page.
                    <br />
                    Google also recommends installing the Google Analytics Opt-out Browser Add-on – [Google Analytics Opt-out](https://tools.google.com/dlpage/gaoptout) – for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics.
                    <br />
                    For more information on the privacy practices of Google, please visit the [Google Privacy Terms](https://policies.google.com/privacy?hl=en) web page.
                    <br />
                    <b>Facebook</b>
                    <br />
                    Facebook remarketing service is provided by Facebook Inc. You can learn more about interest-based advertising from Facebook by visiting this page: [Facebook Help](https://www.facebook.com/help/164968693837950).
                    <br />
                    To opt out of Facebook's interest-based ads, follow these instructions from Facebook: [Facebook Opt-out](https://www.facebook.com/help/568137493302217).
                    <br />
                    Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA [About Ads](http://www.aboutads.info/choices/), the Digital Advertising Alliance of Canada in Canada [Your Ad Choices](http://youradchoices.ca/), or the European Interactive Digital Advertising Alliance in Europe [Your Online Choices](http://www.youronlinechoices.eu/), or opt-out using your mobile device settings.
                    <br />
                    For more information on the privacy practices of Facebook, please visit Facebook's Data Policy: [Facebook Data Policy](https://www.facebook.com/privacy/explanation).

                    <br />
                    <h3> 10. Payments</h3>
                    <br />
                    We may provide paid products and/or services within the Service. In that case, we use a third

                    - party services for payment processing (e.g. payment processors).
                    <br />
                    We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express, and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
                    <br />
                    The payment processors we work with are:
                    <br />
                    <b>Stripe:</b>
                    Their Privacy Policy can be viewed at: [Stripe Privacy Policy](https://stripe.com/us/privacy)

                    <br />
                    <h3> 11. Links to Other Sites </h3>

                    Our Service may contain links to other sites that are not operated by us. If you click a third-party link, you will be directed to that third-party's site. We strongly advise you to review the Privacy Policy of every site you visit.
                    <br />
                    We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.

                    <br />
                    <h3> 12. Children's Privacy</h3>

                    Our Services are not intended for use by children under the age of 13 (“Children”).
                    <br />
                    We do not knowingly collect personally identifiable information from children under 13. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.

                    <br />
                    <h3> 13. Changes to This Privacy Policy</h3>

                    We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
                    <br />
                    We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective, and update the “effective date” at the top of this Privacy Policy.
                    <br />
                    You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.

                    <br />
                    <h3> 14. Contact Us</h3>

                    If you have any questions about this Privacy Policy, please contact us:
                    <br />
                    By email: mahalabizz@gmail.com
                </p>
            </p>
        </div>
    );
};

export default DesignPrivacy;
